development:
  adapter: postgresql
  database: photostore
  host: localhost
  encoding: UTF-8
  username: postgres
  password: 


production:
  adapter: postgresql
  database: photostore
  host: localhost
  encoding: UTF-8
  username: postgres
  password: 