default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: neo
  password: 

development:
  <<: *default
  database: photostore

test:
  <<: *default
  database: photostore_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: neo
  password: 
  database: photostore
