# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94f1f1c9999fe66fd9e3dd653bc0275ece3a3f5e722d07caa6820963d54e139c1712932aa9320d4d96295381b6f1352bd91314966d3ab9654a45ed3ebb10c41d

test:
  secret_key_base: 98a919bf9260235cd69abffd4d88d540c8ece6fc5a00718b45209a1cb71871d942a83258312696580099147c212c46eb1500d67ba2365196435bf8ba1cd09d91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
